### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by banivyom** [BigPino67/Tesseract-MICR-OCR#7]
Hi,
Can you please instruct how to use it to detect MICR codes using python?
What are the steps?

**Comment by BigPino67** [comment]
Tesseract is C++ written. You will have to create or find a python wrapper around C++ to be able to use it in python.

**Comment by banivyom** [comment]
For example, I use tesseract in python with pytesseract library. But it is unable to detect MICR codes. So I want to ask if I can use Tesseract-MICR-OCR in python to detect them? If yes, then how?

**Comment by BigPino67** [comment]
Please, excuse me, I'm not sure to understand you and I'm not familiar at all with Python. Do you mean pytesseract cannot detect MICR at all, or it fails to detect or pytesseract doesn't recognize MICR?

In order to detect MICR, you need to :
1 - Locate MICR Region (for stub or cheques, use this symbol |: to locate the line)
2 - Use the region located and Tesseract with a specific tessdata (trained files pour recognition)

If python can't do MICR recognition at all, you should look to call a libray or an application which can do it for you.

Or, you can run a tesseract commandline and parse the result.

**Comment by BigPino67** [comment]
Closing the bug due to inactivity
